language: python
python: 3.7
install: pip install -r requirements.txt
script: pytest
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: I1yJZh4NPOaGrMgy9NyzbdwdzaVKVGgLCOmSWt1kH+PvUqDZwUyidSBs/B0zIyC9imoDt/q7hZvrEZAyLnXlg+lCUrFW2TmT8KnzykBsKstJxGNF556Odmh8RH4sa9m7dwJaCI95cf2ClTvV1FZMAa+fpQ07oowSa57owBoQnkNFWuft+qOpOC0jh7Tq5e2trALcjLmUlLBPGTAcqCcUynFEJcultpMZHy/y2rlOfg5kVNoym9HIzxJQQmx3xiFvW2AWZ5ceRgNDSLTSYgBQs1ax6WymeK+ndEU6c7djpPqZ3YPV+P3yJ5bTVQP8fBSklkrrboKIjqx7ebnL5pWLCnwbVk+Y3lXOfvvyvonUaZL1QMVJxx6Ru7lxZLvq5yBvXbo00a6Ak0bfiD+7YXEDQz1uBGyIqNckDCWgzVIfFuC5Cp+0kV2hG8kZjdrU2oV3nUNwzjYXSz+7x/Uei61qWlmd4LA8Ds9TwxWnxvdSVgPpJZLtA5CVf5RbEP2jwwOq/k918IZP7nrHeAe6oj7usxijnjwoniNkTE3HQ414k1Pvfe3pc5D5gDe+1T3fxdL3mfIENy7k7dE/1BkmtYF/F05vAF29rAIz72p3EVIs+SE+wsF3M+U0MXKhiuyeNoceEyKvtqJ9csv1Jhl9w7RGo2fhjPq3iProPzg7g3Z6NRk=
